### ISSUE TITLE
Switching groups crashes Firefox

### ISSUE THREAD

**Issue by Keith94** [lambidu/tabs-group-extension#1]
Hi, this add-on looks promising! I just installed it, created a new tab group, switched back to the previous group, but upon doing so Firefox crashes immediately. I'm using Nightly 59.0a1 on Windows.

**Comment by lambidu** [comment]
@Keith94, Just tested in FF Nightly and all works good. 
Can you share crash report ID?
you can find your crash reports by navigating to [about:crashes](about:crashes)
more info about listing/submitting crashes in Firefox is available at [Firefox crashes](https://support.mozilla.org/en-US/kb/firefox-crashes-troubleshoot-prevent-and-get-help#w_get-help-fixing-this-crash)

**Comment by Keith94** [comment]
OK I realized that my issue only happens when switching to a group that has zero tabs (the default when adding a new group). This may be because Firefox thinks there are no existing tabs so it closes the window. I tested this by toggling the `browser.tabs.closeWindowWithLastTab` preference in about:config.

Here's a screencast if that helps: https://1drv.ms/v/s!AgTSVc7lSU2shRs2TUbIvgQd2gcp
