### ISSUE TITLE
Tabs Group 1.0.0 with multiple windows: mis-counts – a focus issue?

### ISSUE THREAD

**Issue by grahamperrin** [lambidu/tabs-group-extension#2]
## Steps to reproduce

1. present the Tabs Group management interface for a window with hundreds of tabs
2. view a window with a single tab
3. click the Tabs Group button

## Expected

- a count of 1 (one)

## Actual result

- the count from the previously viewed window.

## Screen recording

https://www.youtube.com/watch?v=QV6Z16sDoKk – unlisted.

## Environment

Tabs Group 1.0.0 (experimental)

Firefox 56.0.2 (64-bit) on FreeBSD-CURRENT with 1,483 tabs. 

Parts of the recording suggest that eighty-something tabs are loaded, but there's a cosmetic bug in the extension that's used to display the count. The true number was probably less than thirty. 

## Thoughts

Consider this part of the developer's response to <https://addons.mozilla.org/addon/sort-opened-tabs/reviews/933235/>: 

> … check when the focus of the Firefox window changes: the api allowing to change the badge text is limited, there is no way to change the text for a particular Firefox window it seems, it's global to all Firefox windows, thus your problem when switching from a window to another. So I chose this solution: recalculate the count whenever the focus changes. …

**Comment by lambidu** [comment]
@grahamperrin, this extension is NOT meant to group tabs in a specific window only. It must work across all opened windows with same groups.
When you first time open extension popup it will create a group of all currently opened tabs, except pinned one (pinned tabs are NOT managed by this extension) and store that group inside browser store (NOT a window/session).

P. S.
Your video was very useful to me. Thank you for well organized issue ;)
