### ISSUE TITLE
Tabs Group Extension extension (name)

### ISSUE THREAD

**Issue by grahamperrin** [lambidu/tabs-group-extension#3]
Please consider changing the name of the extension: 

- from _Tabs Group Extension_
- to _Tabs Group_

– the word _Extension_ is superfluous. It's categorised under _Extensions_ – 

![2017-11-19 14 05 12](https://user-images.githubusercontent.com/192271/32991416-25d31a12-cd33-11e7-8537-31d6eac4316b.png)

– and so on. 

Thanks

**Comment by lambidu** [comment]
@grahamperrin, yep, you're right!
Changed.
